export { isAlnum } from './is-alnum'
export { isAlpha } from './is-alpha'
export { isAndroid } from './is-android'
export { isCircular } from './is-circular'
export { isDigit } from './is-digit'
export { isEmail, isEmailStrict } from './is-email'
export { isExternalLink, isExternalLinkStrict } from './is-external-link'
export { isFirefox } from './is-firefox'
export { isHarmony } from './is-harmony'
export { isIos } from './is-ios'
export { isMpSchema } from './is-mp-schema'
export { isPhone } from './is-phone'
export { isSafari } from './is-safari'
